### ISSUE TITLE
Partial navigation not working on site content

### ISSUE THREAD

**Issue by sortegamartin** [estruyf/spfx-navigation#2] opened 2019-04-04 14:16 UTC
Hi,

I have an extension with navigation links and when I'm in site content (/_layouts/15/viewlsts.aspx?view=14) and click on a link in the navigation of my extension (Navigation.navigate (url)), only change the URL of the browser but the redirection is not performed.
Could it be that partial navigation is not supported from the content of the site?

Thanks!

**Comment by estruyf** [comment] 2019-04-15 08:47
Will have a check what could be causing the issue

**Comment by estruyf** [comment] 2019-06-04 10:03
@sortegamartin if have tested out this functionality, but cannot reproduce it. It could also be that the SPFx router has fixed the issue already.

Would you be able to test this out again? If it is not working, can you provide more details about how you use it? Are there any error logged?

**Comment by de-angelov** [comment] 2019-07-22 12:54
I have exactly the same problem

**Comment by estruyf** [comment] 2020-02-28 14:28
Finally found a site where I can reproduce this issue. I'm going to investigate what can be done.

**Comment by estruyf** [comment] 2020-02-28 15:50
Should now have been fixed in the latest version

**Closed** 2020-02-28 15:49 UTC
